const dummyData = [
  {
    id: 1,
    img: "./",
    score: 66,
    title: "protein bar",
    type: "product",
    ingredients: [
      { title: "allergens", score: 1 },
      { title: "concerns", score: 3 },
      { title: "additives", score: 6 },
      { title: "sugar", score: 2 },
      { title: "refineoil", score: 3 },
    ],
    posFacts: ["Whole Grains"],
    negFacts: ["Added Sodium", "Preservatives", "Refined Oil"],
  },
  {
    id: 2,
    img: "./",
    score: 37,
    title: "cold drink",
    type: "product",
    ingredients: [
      { title: "allergens", score: 1 },
      { title: "concerns", score: 3 },
      { title: "additives", score: 6 },
      { title: "sugar", score: 2 },
      { title: "refineoil", score: 3 },
    ],
    posFacts: ["Whole Grains"],
    negFacts: ["Added Sodium", "Preservatives", "Refined Oil"],
  },
  {
    id: 3,
    img: "./",
    score: 22,
    title: "chips",
    type: "product",
    ingredients: [
      { title: "allergens", score: 1 },
      { title: "concerns", score: 3 },
      { title: "additives", score: 6 },
      { title: "sugar", score: 2 },
      { title: "refineoil", score: 3 },
    ],
    posFacts: ["Whole Grains"],
    negFacts: ["Added Sodium", "Preservatives", "Refined Oil"],
  },
  {
    id: 4,
    img: "./",
    score: 95,
    title: "juice",
    type: "product",
    ingredients: [
      { title: "allergens", score: 1 },
      { title: "concerns", score: 3 },
      { title: "additives", score: 6 },
      { title: "sugar", score: 2 },
      { title: "refineoil", score: 3 },
    ],
    posFacts: ["Whole Grains"],
    negFacts: ["Added Sodium", "Preservatives", "Refined Oil"],
  },
  {
    id: 5,
    img: "./",
    score: 50,
    title: "chocolate",
    type: "product",
    ingredients: [
      { title: "allergens", score: 1 },
      { title: "concerns", score: 3 },
      { title: "additives", score: 6 },
      { title: "sugar", score: 2 },
      { title: "refineoil", score: 3 },
    ],
    posFacts: ["Whole Grains"],
    negFacts: ["Added Sodium", "Preservatives", "Refined Oil"],
  },
  {
    id: 6,
    img: "./",
    score: 18,
    title: "oil",
    type: "product",
    ingredients: [
      { title: "allergens", score: 1 },
      { title: "concerns", score: 3 },
      { title: "additives", score: 6 },
      { title: "sugar", score: 2 },
      { title: "refineoil", score: 3 },
    ],
    posFacts: ["Whole Grains"],
    negFacts: ["Added Sodium", "Preservatives", "Refined Oil"],
  },
  {
    id: 7,
    img: "./",
    score: 85,
    title: "strawberry",
    type: "product",
    ingredients: [
      { title: "allergens", score: 1 },
      { title: "concerns", score: 3 },
      { title: "additives", score: 6 },
      { title: "sugar", score: 2 },
      { title: "refineoil", score: 3 },
    ],
    posFacts: ["Whole Grains"],
    negFacts: ["Added Sodium", "Preservatives", "Refined Oil"],
  },
  {
    id: 8,
    img: "./",
    score: 45,
    title: "candy",
    type: "product",
    ingredients: [
      { title: "allergens", score: 1 },
      { title: "concerns", score: 3 },
      { title: "additives", score: 6 },
      { title: "sugar", score: 2 },
      { title: "refineoil", score: 3 },
    ],
    posFacts: ["Whole Grains"],
    negFacts: ["Added Sodium", "Preservatives", "Refined Oil"],
  },
  {
    id: 9,
    img: "./",
    score: 68,
    title: "food",
    type: "category",
    ingredients: [
      { title: "allergens", score: 1 },
      { title: "concerns", score: 3 },
      { title: "additives", score: 6 },
      { title: "sugar", score: 2 },
      { title: "refineoil", score: 3 },
    ],
    posFacts: ["Whole Grains"],
    negFacts: ["Added Sodium", "Preservatives", "Refined Oil"],
  },
  {
    id: 10,
    img: "./",
    score: 45,
    title: "beverages",
    type: "category",
    ingredients: [
      { title: "allergens", score: 1 },
      { title: "concerns", score: 3 },
      { title: "additives", score: 6 },
      { title: "sugar", score: 2 },
      { title: "refineoil", score: 3 },
    ],
    posFacts: ["Whole Grains"],
    negFacts: ["Added Sodium", "Preservatives", "Refined Oil"],
  },
  {
    id: 11,
    img: "./",
    score: 57,
    title: "snacks",
    type: "category",
    ingredients: [
      { title: "allergens", score: 1 },
      { title: "concerns", score: 3 },
      { title: "additives", score: 6 },
      { title: "sugar ", score: 2 },
      { title: "refineoil", score: 3 },
    ],
    posFacts: ["Whole Grains"],
    negFacts: ["Added Sodium", "Preservatives", "Refined Oil"],
  },
];
